name: Archive Links

on:
  push:
    paths:
      - '**.yaml'
      - '**.yml'
  workflow_dispatch:  # Allow manual triggering

jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history to detect file changes
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml requests beautifulsoup4
          
      - name: Run archiving script
        run: python scripts/archive_links.py
      
      - name: Check for changes
        id: check_changes
        run: |
          git diff --quiet logs/ || echo "changes=true" >> $GITHUB_OUTPUT
      
      - name: Commit archive logs
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add logs/
          git commit -m "Update archived links log [skip ci]"
          git push